# Mengambil inventory dari AWS EC2

plugin: amazon.aws.aws_ec2
regions:
  - ap-southeast-1  # Sesuaikan dengan region Anda
keyed_groups:
  # Membuat grup berdasarkan nilai dari tag 'Project'
  # Contoh: jika ada VM dengan tag Project: iac-thesis, akan ada grup [iac-thesis]
  - key: tags.Project
    prefix: tag_Project_
filters:
  # Hanya mengambil instance yang sedang berjalan
  instance-state-name: running
compose:
  # Mengatur variabel ansible_host dengan alamat IP publik dari instance
  ansible_host: public_ip_address