plugin: google.cloud.gcp_compute
auth_kind: serviceaccount
service_account_file: "{{ lookup('vars', 'gcp_credentials_file', vault_id='gcp') }}"
projects:
  - eminent-kit-463510-a3 
zones:
  - asia-southeast1-a 
keyed_groups:
  - key: labels.project
    prefix: label_project_
filters:
  - status = RUNNING
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP