plugin: google.cloud.gcp_compute
auth_kind: serviceaccount
projects:
  - eminent-kit-463510-a3
service_account_file: /root/Ansible-Otomation/gcp-credentials.json
hostnames:
  - name
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
keyed_groups:
  - key: labels.project
    prefix: project