- name: Create AWS Security Group
  amazon.aws.ec2_security_group:
    name: "web-sg"
    description: "Allow HTTP and SSH from Control Node"
    region: ap-southeast-1 # <-- Ganti dengan region Anda
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "152.42.169.182/32"

- name: Create AWS Launch Template
  amazon.aws.ec_launch_template:
    name: "web-server-template"
    region: "ap-southeast-1"
    key_name: "ansible-key" 
    instance_type: "t3.micro"
    ami_id: "ami-0b8607d2721c94a77"
    network_interfaces:
      - associate_public_ip_address: yes
        groups:
          - "web-sg"
    tag_specifications:
      - resource_type: instance
        tags:
          Project: "multicloud-chaos"
          Name: "aws-web-instance" 

- name: Create AWS Auto Scaling Group for Auto Healing
  community.aws.ec2_asg:
    name: "web-asg"
    region: ap-southeast-1
    launch_template:
      launch_template_name: "web-server-template"
    min_size: 1
    max_size: 1
    desired_capacity: 1
    availability_zones: ["ap-southeast-1a"] 
    health_check_type: EC2
    health_check_period: 300