- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  changed_when: false 

- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Ensure Nginx service is started and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Allow HTTP traffic on UFW firewall
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp
    comment: "Allow NGINX HTTP traffic"

- name: Create custom index page with hostname
  ansible.builtin.copy:
    content: "<h1>Hello from {{ ansible_facts.hostname }} on {{ ansible_facts.distribution }}</h1>"
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'