# roles/web_server/tasks/main.yml
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  changed_when: false # Agar tidak melaporkan 'changed' hanya karena update cache

- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Ensure Nginx service is started and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Allow HTTP traffic on UFW firewall
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp
    comment: "Allow NGINX HTTP traffic"