- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  changed_when: false

- name: Install Nginx and Stress Tools
  ansible.builtin.apt:
    name:
      - nginx
      - stress-ng
    state: present

- name: Ensure Nginx service is started and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes