- name: Create GCP Firewall Rule
  google.cloud.gcp_compute_firewall:
    name: "{{ gcp_firewall_name }}"
    project: "{{ gcp_project_id }}"
    allowed:
      - ip_protocol: "tcp"
        ports: ["80", "22"]
    source_ranges: ["0.0.0.0/0"]
    target_tags: ["{{ gcp_network_tag }}"]
    auth_kind: "serviceaccount"
    service_account_contents: "{{ gcp_service_account_info }}"

- name: Create GCP Instance Template
  google.cloud.gcp_compute_instance_template:
    name: "{{ gcp_instance_template_name }}"
    project: "{{ gcp_project_id }}"
    properties:
      machine_type: "{{ gcp_machine_type }}"
      disks:
        - auto_delete: true
          boot: true
          initialize_params:
            source_image: "{{ gcp_source_image }}"
      network_interfaces:
        - access_configs:
            - name: 'External NAT'
              type: 'ONE_TO_ONE_NAT'
      labels:
        "{{ gcp_project_label }}": "{{ gcp_project_value }}"
      tags:
        items: ["{{ gcp_network_tag }}"]
    auth_kind: "serviceaccount"
    service_account_contents: "{{ gcp_service_account_info }}"
  register: template_result

- name: Create GCP Managed Instance Group
  google.cloud.gcp_compute_instance_group_manager:
    name: "{{ gcp_mig_name }}"
    zone: "{{ gcp_zone }}"
    project: "{{ gcp_project_id }}"
    instance_template:
      selfLink: "{{ template_result.selfLink }}"
    base_instance_name: "{{ gcp_instance_base_name }}"
    target_size: 1
    auth_kind: "serviceaccount"
    service_account_contents: "{{ gcp_service_account_info }}"