- name: Run Auto Healing and Chaos Experiments
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../vars/main.yml
  vars:
    aws_instance_group: "{{ aws_project_tag }}_{{ aws_project_value }}"
    gcp_instance_group: "{{ gcp_project_label }}_{{ gcp_project_value }}"
  tasks:
    - name: Run chaos experiments
      ansible.builtin.include_role:
        name: chaos