- name: Teardown All Auto Healing Infrastructure
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../vars/main.yml
    - ../vars/aws_secrets.yml
    - ../vars/gcp_secrets.yml
  tasks:
    # --- AWS CLEANUP ---
    - name: AWS | Delete Auto Scaling Group
      community.aws.ec2_asg:
        name: "{{ aws_asg_name }}"
        state: absent
        region: "{{ aws_region }}"
      ignore_errors: yes

    - name: AWS | Wait for instances to terminate before deleting LT
      ansible.builtin.pause:
        seconds: 60

    - name: AWS | Delete Launch Template
      amazon.aws.ec2_launch_template:
        name: "{{ aws_lt_name }}"
        state: absent
        region: "{{ aws_region }}"
      ignore_errors: yes

    - name: AWS | Delete Security Group
      amazon.aws.ec2_security_group:
        name: "{{ aws_sg_name }}"
        state: absent
        region: "{{ aws_region }}"
      ignore_errors: yes

    # --- GCP CLEANUP ---
    - name: GCP | Delete Managed Instance Group
      google.cloud.gcp_compute_instance_group_manager:
        name: "{{ gcp_mig_name }}"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project_id }}"
        state: absent
        service_account_contents: "{{ gcp_service_account_info }}"
      ignore_errors: yes

    - name: GCP | Delete Instance Template
      google.cloud.gcp_compute_instance_template:
        name: "{{ gcp_instance_template_name }}"
        project: "{{ gcp_project_id }}"
        state: absent
        service_account_contents: "{{ gcp_service_account_info }}"
      ignore_errors: yes

    - name: GCP | Delete Firewall Rule
      google.cloud.gcp_compute_firewall:
        name: "{{ gcp_firewall_name }}"
        project: "{{ gcp_project_id }}"
        state: absent
        service_account_contents: "{{ gcp_service_account_info }}"
      ignore_errors: yes